steps:
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['install', './gcb-helm-cronjob']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=test'
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=test'
